
all: day04

day01:
	time nim c --out:./nim/build/main nim/day01.nim
	time ./nim/build/main
	time python python/day01.py

day02:
	time nim c --out:./nim/build/main nim/day02.nim
	time ./nim/build/main
	time python python/day02.py

day03:
	time nim c --out:./nim/build/main nim/day03.nim
	time ./nim/build/main
	time python python/day03.py

day04:
	# time nim c --out:./nim/build/main nim/day04.nim
	# time ./nim/build/main
	time python python/day04.py
