
all: day06

day01:
	time nim c --out:./nim/build/main nim/day01.nim
	time ./nim/build/main

day02:
	time nim c --out:./nim/build/main nim/day02.nim
	time ./nim/build/main

day03:
	time nim c --out:./nim/build/main nim/day03.nim
	time ./nim/build/main

day04:
	time nim c --out:./nim/build/main nim/day04.nim
	time ./nim/build/main

day05:
	time nim c --out:./nim/build/main nim/day05.nim
	time ./nim/build/main

day06:
	time nim c --out:./nim/build/main nim/day06.nim
	time ./nim/build/main
