
all: day03

day01:
	time nim c --out:./nim/build/main nim/day01.nim
	time ./nim/build/main

day02:
	time nim c --out:./nim/build/main nim/day02.nim
	time ./nim/build/main

day03:
	time nim c --out:./nim/build/main nim/day03.nim
	time ./nim/build/main
